-- انسخي هذا الكود بالكامل والصقيه في Supabase Dashboard -> SQL Editor -> New query
-- ثم اضغطي RUN

create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null default 'robes',
  price numeric not null,
  img text,
  description text,
  created_at timestamptz default now()
);

create table orders (
  id bigint generated by default as identity primary key,
  date timestamptz default now(),
  customer jsonb,
  delivery_type text,
  shipping_fee numeric,
  subtotal numeric,
  items jsonb,
  total numeric,
  created_at timestamptz default now()
);

-- تعطيل الحماية الصفية (RLS) لتبسيط الوصول من الموقع مباشرة
-- ملاحظة: هذا يعني أن أي شخص يملك مفتاح anon (المتاح أصلاً داخل كود الموقع)
-- يستطيع نظريًا قراءة/تعديل هذه الجداول عبر واجهة Supabase البرمجية مباشرة.
-- مقبول لمتجر صغير في مرحلته الأولى، لكن للحماية الأقوى لاحقًا يُنصح
-- بإضافة سياسات RLS مخصصة أو نقل عمليات الكتابة (الحذف/الإضافة) إلى وظيفة خادم Edge Function.
alter table products disable row level security;
alter table orders disable row level security;
